coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 99%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        if_ci_failed: error
